export const AuthenticationLabel = {
    Email: "Email",
    Password: "Password",
    Token: "token",
    AdminId: "adminId",
    AuthePageTitle: "SignIn | Quizown",
    WelcomeMessage: "Welcome Back !",
    AuthEmailInputLabel: "Email",
    AuthEmailInputPlaceholder: "email",
    AuthPasswordInputLabel: "Password",
    AuthPasswordInputPlaceholder: "password",
    SignIn: "Sign In",
    Logout: "Logout",
    ValidationPlaceholderCurrentPasswordValue: "Current password",
    ValidationPlaceholderNewPasswordValue: "New password",
    ValidationPlaceholderConfirmNewPasswordValue: "Confirm new password",
    NewPasswordMatchingName: "newPassword",
    NewPasswordShouldMatchProp: "New password",
    ConfirmNewPasswordShouldMatchProp: "confirm new password",
    PasswordNameForLength: "Password",
    PasswordLengthForLength: "8",
    PasswordNameForComplexity: "Password",

    CurrentPasswordLabel: "Current password",
    CurrentPasswordPlaceholderValue: "current password",
    NewPasswordLabel: "New password",
    NewPasswordPlaceholderValue: "new password",
    ConfirmNewPasswordLabel: "Confirm new password",
    ConfirmNewPasswordPlaceholderValue: "confirm new password",
    ChangePasswordButton: "Change Password",
    ChangePasswordHeading: "Change Password",
    ChangePasswordPageTitle: "Change password | Quizown",

    ImageTypeForAdminProfile: "image/",
    ValidationPlaceholderAdminNameValue: "Name",
    ValidationPlaceholderAdminEmailValue: "Email",
    ValidationPlaceholderAdminPhoneNumberValue: "Phone number",
    NameForFormData: "name",
    EmailForFormData: "email",
    PhoneForFormData: "contact_no",
    AvatarForFormData: "profile_image",
    ProfilePageTitle: "Profile | Quizown",
    AdminProfileHeading: "Admin Profile",
    AdminNameLabel: "Name",
    AdminNamePlaceholderValue: "name",
    AdminEmailLabel: "Email",
    AdminEmailPlaceholderValue: "email",
    AdminPhoneNumberLabel: "Phone number",
    AdminPhoneNumberPlaceholderValue: "phone number",
    UpdateButton: "Update",
    
    AdminInProfileDropDown: "Admin",
    FounderInProfileDropDown: "Founder",
    WelcomeMessageInProfileDropDown: "Welcome",
    ProfileMenuInProfileDropDown: "Profile",
    ChangePasswordMenuInProfileDropDown: "Change password",
    LogoutMenuInProfileDropDown: "Logout",
    AreYouSureYouWantToLogout: "Are you sure you want to logout?",
    YouAreLogoutSuccessfully: "You are logout successfully.",
}