export const QuizzesLabel = {
  QuizzesPageTitle: "Quizzes | Quizown",
  Quizzes: "Quizzes",
  Title: "Title",
  Domain: "Domain",
  Type: "Type",
  Question: "No. of questions are required.",
  BonusQuestion: "No. of bonus questions are required.",
  MaximumParticipant: "Maximum participant",
  QuestionValidation: "No. of questions",
  DurationFormatValidation: "Duration must be in MM:SS format",
  BonusQuestionValidation: "No. of bonus questions",
  Duration: "Duration",
  DifficultyLevel: "Difficulty Level",
  StartDate: "Start date and time",
  EndDate: "End date and time",
  VisibilityStatus: "Visibility Status",
  AddQuiz: "Add Quiz",
  EditQuiz: "Edit Quiz",
  EditStatus: "Status",
  EndDateValidation: "End date and time",
  StartDateValidation: "start date and time",
  DurationValidation: "Duration",
  dataNotFound: "Sorry! There Is No Questions",
  AddBonusQuestion: "Add Bonus Question",
  EditBonusQuestion: "Edit Bonus Question",
  ImageTypeForQuiz: "image/",
  DefaultQuizImageAlt: "Image",
  MaximumParticipantValidation: "No. of maximum participant",
  QuizImage: "Quiz image",
  Tournament: "Tournament",
  Public: "Public",
  Private: "Private",
  AdminPrivateQuizWarningMessage: "Sorry! You're not allowed to create private quizzes.",
};

export const QuizHeader = {
  Title: "Title",
  Domain: "Domain",
  Type: "Type",
  QuizQuestion: "Questions",
  BonusQuizQuestion: "Bonus Questions",
  VisibilityStatus: "Status",
  TournamentStatus: "Tournament Status",
};

export const QuizKey = {
  Title: "title",
  Domain: "domain_name",
  Type: "type",
  QuizQuestion: "total_draft_questions",
  BonusQuizQuestion: "bonus_questions",
  VisibilityStatus: "status",
  TournamentStatus: "tournament_Status",
};

export const QuizzesUIConstants = {
  AddQuiz: "Add Quiz",
  EditQuiz: "Edit Quiz",
  QuizNavigate: "Quiz",
  AddQuizNavigate: "Add Quiz",
  EditQuizNavigate: "Edit Quiz",
  SelectAll: "Select All",
  QuizImage: "Quiz Image",
  TitleInputLabel: "Title",
  TitleInputPlaceholder: "title",
  DomainLabel: "Domain",
  DomainPlaceholder: "domain",
  TypeLabel: "Type",
  TypePlaceholder: "type",
  QuestionsLabel: "Number of Questions",
  QuestionsPlaceholder: "number of questions",
  BonusQuestionsLabel: "Number of Bonus Questions",
  BonusQuestionsPlaceholder: "number of bonus questions",
  MaximumParticipantLabel: "Number of maximum participant",
  MaximumParticipantPlaceholder: "number of maximum participant",
  DurationLabel: "Duration",
  DurationPlaceholder: "MM:SS (e.g., 1:30, 20:10, 120:40)",
  DifficultyLevelLabel: "Difficulty Level",
  DifficultyLevelPlaceholder: "difficulty level",
  StartDateTimeInputLabel: "Start Date and Time",
  EndDateTimeInputLabel: "End Date and Time",
  AreYouSureYouWantTo: "Are you sure you want to",
  ThisQuiz: "this quiz?",
  QuizDetails: "Quiz Details",
  QuizQuestions: "Quiz Questions",
  Gold: "Gold",
  PublishThisQuiz: "publish this quiz?",
  QuizStatusPublish: "publish",
  Add: "Add",
  QuestionsIntoQuiz: "questions to publish a quiz.",
  SaveAsDraft: "Save as draft",
  AddAtleastOneQuestionToDraftAQuiz:
    "Add at least 1 question to draft a quiz.",
  QuizDetailsHeading: "'s Details",
  Quiz: "Quiz",
  View: "View Quiz",
  GemSign: ":",
  Questions: "Questions",
  BonusQuestions: "Bonus Questions",
  MaxParticipants: "Max Participants",
  Status: "Status",
  Draft: "Draft",
  ForTournament: "For Tournament",
  True: "True",
};

export const TournamentOptions = [
  { id: "true", value: "true", label: "Yes" },
  { id: "false", value: "false", label: "No" },
];

export const QuizOption = [
  { label: "Public", value: "Public" },
  { label: "Private", value: "Private" },
  { label: "Tournament", value: "Tournament" },
];
export const StatusOption = [
  { label: "Active", value: "Active" },
  { label: "Inactive", value: "Inactive" },
];
export const DifficultyLevelOption = [
  { label: "Practice/Beginner", value: "Practice/Beginner" },
  { label: "Moderate", value: "Moderate" },
  { label: "Expert", value: "Expert" },
];